'use client'

import type { PropsWithChildren } from 'react'
import { Layout } from 'antd'

import 'antd/dist/reset.css'
import { RootStyleRegistry } from '@/components/root-style-registry'
import { TopHeader } from '@/components/header'
import { Content } from 'antd/es/layout/layout'

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="pt-BR">
      <head>
        <title>The Rick and Morty GraphQL</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </head>
      <body>
        <RootStyleRegistry>
          <Layout className="layout">
            <TopHeader />
            <Content style={{ padding: '30px 50px' }}>
              {children}
            </Content>
          </Layout>
        </RootStyleRegistry>
      </body>
    </html>
  )
}
